---
#install zabbix - centos 7.5 with enabled SELinux
- hosts: all
  become: yes
  tasks: 
    - name: update all packages
      yum:
        name: "*"
        update_cache: yes
        state: latest
    - name: add repository - zabbix
      #https://docs.ansible.com/ansible/latest/modules/yum_module.html
      #However, if one of the packages adds a new yum repository 
      #that the other packages come from (such as epel-release) 
      #then that package needs to be installed in a separate task. This mimics yum’s command line behaviour.
      yum:
        name: https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
        state: present 
   
    - name: ensure a list of packages installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - yum-utils
        - httpd
        - curl
        - vim
        - mc
        - mariadb-server
        - policycoreutils-python
        - setroubleshoot 
        - setroubleshoot-server
        - MySQL-python
        

    - name: zabbix frontend additional packages enable repository of optional rpms
      shell: yum-config-manager --enable rhel-7-server-optional-rpms
    - name: install zabbix
      yum:
        name: "{{ zbx_packages }}"
        state: present
      vars:
        zbx_packages:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent
    - name: database changes
      
    - name: services enabled
      service:
       name: "{{ enabled_items }}"
       enabled: yes
      vars:
       enebled_items:
       - mariadb-server
       - httpd
       - zabbix-server
       - zabbix-agent
    - name: services start
      service:
       name: "{{ enabled_items }}"
       enabled: yes
      vars:
       enebled_items:
       - mariadb-server
       - httpd
       - zabbix-server
       - zabbix-agent
    - name: services restart
      #sudo service auditd restart
      service:
       name: "{{ restart_items }}"
       state: reloaded
      vars:
       restart_items:
       - auditd
       - httpd