---
#install zabbix - centos 7.5 with enabled SELinux
- hosts: all
  become: yes
  vars:
   mysql_root_password: enter@your@password111
   mysql_zabbix_password: enter@your@password123 
  tasks: 
    - name: Update all packages
      yum:
        name: "*"
        update_cache: yes
        state: latest
    - name: Add repository - zabbix 3.4.2
      #https://docs.ansible.com/ansible/latest/modules/yum_module.html
      #However, if one of the packages adds a new yum repository 
      #that the other packages come from (such as epel-release) 
      #then that package needs to be installed in a separate task. This mimics yum’s command line behaviour.
      yum:
        name: https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
        state: present 
   
    - name: Ensure a list of packages installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - yum-utils
        - httpd
        - curl
        - vim
        - mc
        - mariadb-server
        - policycoreutils-python
        - setroubleshoot 
        - setroubleshoot-server
        - MySQL-python
        - libsemanage-python
        

    - name: Zabbix frontend additional packages enable repository of optional rpms
      shell: yum-config-manager --enable rhel-7-server-optional-rpms
    - name: Install zabbix
      yum:
        name: "{{ zbx_packages }}"
        state: present
      vars:
        zbx_packages:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent
    - name: Services enabled
      service:
       name: "{{ enabled_items }}"
       enabled: yes
      vars:
       enebled_items:
       - mariadb-server
       - httpd
       - zabbix-server
       - zabbix-agent
    - name: Services start
      service:
       name: "{{ started_items }}"
       state: started
      vars:
       started_items:
       - mariadb-server
       - httpd
       - zabbix-server
       - zabbix-agent
    - name: Services restart
      service:
       name: "{{ restart_items }}"
       state: reloaded
      vars:
       restart_items:
       - auditd
       - httpd
    - name: Database changes
    #https://stackoverflow.com/questions/25136498/ansible-answers-to-mysql-secure-installation
      yum: name=MySQL-python state=present
      when: ansible_os_family == 'RedHat'
    - name: Sets the root password 
      mysql_user: user=root password="{{ mysql_root_password }}" host=localhost
    - name: Deletes anonymous MySQL server user for localhost
      mysql_user: user="" state="absent"  
    - name: Secures the MySQL root user - disallow root login remotely
      mysql_user: user="root" password="{{ mysql_root_password }}" host="{{root_host_list}}"
      vars:
        root_host_list:
        - ::1
        - localhost
        - 127.0.0.1
    - name: Removes the MySQL test database
      mysql_db: db=test state=absent  
    - name: Create zabbix database
      mysql_db: db=zabbix state=present encoding=utf8